<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Dapper" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Npgsql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Persistence/Migrations/*.sql" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SocAlytics.Platform.Migrator" />
		<InternalsVisibleTo Include="SocAlytics.Platform.Integration.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SocAlytics.Platform.Application\SocAlytics.Platform.Application.csproj" />
		<ProjectReference Include="..\SocAlytics.Platform.Domain\SocAlytics.Platform.Domain.csproj" />
	</ItemGroup>
</Project>
