import assert from 'node:assert/strict';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import test from 'node:test';

import {
  parseCapabilityDefinition,
  parseCapabilityTasks,
  validateCapabilitySet,
} from './openspec-change-core.mjs';

const capabilityIds = [
  'architecture',
  'audit',
  'design',
  'implementation',
  'strategy',
  'verification',
];
const definitions = new Map(capabilityIds.map((id) => [
  id,
  parseCapabilityDefinition(
    readFileSync(
      new URL(`../../openspec/capabilities/${id}.md`, import.meta.url),
      'utf8',
    ),
    id,
  ),
]));

test('validates every execution capability contract', () => {
  const definitionSchema = JSON.parse(readFileSync(
    new URL('../../openspec/capabilities/schemas/capability-v1.schema.json', import.meta.url),
    'utf8',
  ));
  const resultSchema = JSON.parse(readFileSync(
    new URL('../../openspec/capabilities/schemas/capability-result-v1.schema.json', import.meta.url),
    'utf8',
  ));
  const operationResultSchema = JSON.parse(readFileSync(
    new URL('./schemas/operation-result-v1.schema.json', import.meta.url),
    'utf8',
  ));
  assert.equal(definitionSchema.properties.version.const, 1);
  assert.equal(resultSchema.properties.schema.const, 'capability-result-v1');
  assert.equal(resultSchema.properties.operation.const, 'apply');
  assert.equal(operationResultSchema.properties.schema.const, 'operation-result-v1');

  for (const definition of definitions.values()) {
    assert.ok(definition.operations.includes('apply'));
  }
  assert.deepEqual(
    [...definitions.values()]
      .filter(({ composition }) => composition === 'exclusive')
      .map(({ id }) => id),
    ['audit', 'verification'],
  );
  assert.deepEqual(
    validateCapabilitySet(
      ['architecture', 'implementation'].map((id) => definitions.get(id)),
      'apply',
    ),
    {
      ids: ['architecture', 'implementation'],
      mutation: 'scoped',
      isolation: 'shared',
      resultSchema: 'schemas/capability-result-v1.schema.json',
    },
  );
});

test('keeps only the generated OpenSpec cloud profile', () => {
  const agentDirectory = new URL('../agents/', import.meta.url);
  const customProfiles = [
    'openspec-cloud',
    'soca-architect',
    'soca-auditor',
    'soca-designer',
    'soca-developer',
    'soca-strategist',
    'soca-verifier',
  ];
  for (const name of customProfiles) {
    assert.equal(existsSync(new URL(`${name}.agent.md`, agentDirectory)), false);
  }
  const content = readFileSync(
    new URL('openspec.agent.md', agentDirectory),
    'utf8',
  );
  assert.match(content, /Generated by OpenSpec/);
  assert.match(content, /^name: OpenSpec$/m);
  assert.doesNotMatch(content, /openspec\/capabilities|soca-/);
});

test('requires capability declarations on every active task', () => {
  const changesDirectory = new URL('../../openspec/changes/', import.meta.url);
  for (const entry of readdirSync(changesDirectory, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'archive') continue;
    const tasksPath = new URL(`${entry.name}/tasks.md`, changesDirectory);
    if (!existsSync(tasksPath)) continue;
    const tasks = parseCapabilityTasks(readFileSync(tasksPath, 'utf8'));
    assert.ok(tasks.length > 0, `${entry.name} must contain numbered tasks`);
    for (const task of tasks) {
      assert.doesNotThrow(
        () => validateCapabilitySet(
          task.capabilities.map((id) => definitions.get(id)),
          'apply',
        ),
        `${entry.name} task ${task.id} must have a compatible capability set`,
      );
    }
  }
});
