<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SocAlytics.Platform.Persistence\SocAlytics.Platform.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Migrations\*.sql" LogicalName="SocAlytics.Platform.AgentOrchestration.Migrations.%(Filename)%(Extension)" />
	</ItemGroup>
</Project>