<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SocAlytics.Platform.Persistence\SocAlytics.Platform.Persistence.csproj" />
		<EmbeddedResource Include="Migrations\0001_initial.sql" />
	</ItemGroup>
</Project>