<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SocAlytics.Platform.Persistence\SocAlytics.Platform.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="0001_initial_schema.sql" LogicalName="SocAlytics.Platform.Registry.Migrations.0001_initial_schema.sql" />
	</ItemGroup>
</Project>