CREATE SCHEMA club AUTHORIZATION club_owner;
REVOKE ALL ON SCHEMA club FROM PUBLIC;
GRANT USAGE ON SCHEMA club TO club_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE club_owner IN SCHEMA club GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO club_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE club_owner IN SCHEMA club GRANT USAGE, SELECT ON SEQUENCES TO club_runtime;
